package com.messi.appshelper.dao;

import android.graphics.drawable.Drawable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table APP_INFO.
 */
public class AppInfo {

    private Long id;
    private String appName;
    private String packageName;
    private String versionName;
    private Integer versionCode;
    private String defaultType;
    private String customType;
    private Integer systemNo;
    private String lastOpenTime;
    private Integer startTimes;
    private String backup1;
    private String backup2;
    private String backup3;
    private Drawable appIcon;

    public Drawable getAppIcon() {
		return appIcon;
	}

	public void setAppIcon(Drawable appIcon) {
		this.appIcon = appIcon;
	}

	public AppInfo() {
    }

    public AppInfo(Long id) {
        this.id = id;
    }

    public AppInfo(Long id, String appName, String packageName, String versionName, Integer versionCode, String defaultType, String customType, Integer systemNo, String lastOpenTime, Integer startTimes, String backup1, String backup2, String backup3) {
        this.id = id;
        this.appName = appName;
        this.packageName = packageName;
        this.versionName = versionName;
        this.versionCode = versionCode;
        this.defaultType = defaultType;
        this.customType = customType;
        this.systemNo = systemNo;
        this.lastOpenTime = lastOpenTime;
        this.startTimes = startTimes;
        this.backup1 = backup1;
        this.backup2 = backup2;
        this.backup3 = backup3;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getVersionName() {
        return versionName;
    }

    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    public Integer getVersionCode() {
        return versionCode;
    }

    public void setVersionCode(Integer versionCode) {
        this.versionCode = versionCode;
    }

    public String getDefaultType() {
        return defaultType;
    }

    public void setDefaultType(String defaultType) {
        this.defaultType = defaultType;
    }

    public String getCustomType() {
        return customType;
    }

    public void setCustomType(String customType) {
        this.customType = customType;
    }

    public Integer getSystemNo() {
        return systemNo;
    }

    public void setSystemNo(Integer systemNo) {
        this.systemNo = systemNo;
    }

    public String getLastOpenTime() {
        return lastOpenTime;
    }

    public void setLastOpenTime(String lastOpenTime) {
        this.lastOpenTime = lastOpenTime;
    }

    public Integer getStartTimes() {
        return startTimes;
    }

    public void setStartTimes(Integer startTimes) {
        this.startTimes = startTimes;
    }

    public String getBackup1() {
        return backup1;
    }

    public void setBackup1(String backup1) {
        this.backup1 = backup1;
    }

    public String getBackup2() {
        return backup2;
    }

    public void setBackup2(String backup2) {
        this.backup2 = backup2;
    }

    public String getBackup3() {
        return backup3;
    }

    public void setBackup3(String backup3) {
        this.backup3 = backup3;
    }

	@Override
	public String toString() {
		return "AppInfo [id=" + id + ", appName=" + appName + ", packageName="
				+ packageName + ", versionName=" + versionName
				+ ", versionCode=" + versionCode + ", defaultType="
				+ defaultType + ", customType=" + customType + ", systemNo="
				+ systemNo + ", lastOpenTime=" + lastOpenTime + ", startTimes="
				+ startTimes + ", backup1=" + backup1 + ", backup3=" + backup3
				+ ", appIcon=" + appIcon + "]";
	}

    
}
